# Generated by Django 4.1.4 on 2023-04-30 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDescription', models.TextField()),
                ('eventSummary', models.CharField(max_length=500)),
                ('eventtitle', models.CharField(max_length=100)),
                ('eventDate', models.DateField()),
                ('eventTime', models.TimeField()),
                ('eventSeatingCapacity', models.IntegerField()),
                ('eventVenue', models.TextField()),
                ('registrationLink', models.URLField()),
                ('is_referral', models.BooleanField(default=False)),
                ('contactName1', models.CharField(default='dummy user', max_length=100)),
                ('contactName2', models.CharField(blank=True, max_length=100, null=True)),
                ('contactNumber1', models.CharField(default='0000000000', max_length=10)),
                ('contactNumber2', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
            ],
        ),
        migrations.CreateModel(
            name='EventLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EventLikes',
                'verbose_name_plural': 'EventLikes',
            },
        ),
    ]
