# Generated by Django 4.2.3 on 2023-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='main_img',
            field=models.ImageField(upload_to='events/imag/'),
        ),
        migrations.AlterField(
            model_name='eventsimage',
            name='image',
            field=models.ImageField(upload_to='events/imag/'),
        ),
    ]
