# Generated by Django 4.1.4 on 2023-04-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Students',
        ),
    ]
