# Generated by Django 4.2.3 on 2023-07-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='image',
            field=models.ImageField(default=1, upload_to='commitee/'),
            preserve_default=False,
        ),
    ]
