# Generated by Django 4.1.4 on 2023-04-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0003_user_delete_committee_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='committee',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sapid',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True),
        ),
    ]
