# Generated by Django 4.1.7 on 2023-04-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0005_userprofile_member_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginreg.user'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginreg.user'),
        ),
    ]
